apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dse
spec:
  selector:
    matchLabels:
      app: dse
  serviceName: "dse"
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dse
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: dse
        image: datastax/dse-server:6.0.0-openjdk8
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "2"
            memory: "2000Mi"
        env:
        - name: DS_LICENSE
          value: accept
        - name: SEEDS
          value: dse-0.dse.default.svc.cluster.local,dse-1.dse.default.svc.cluster.local
        - name: CLUSTER_NAME
          value: "My_Cluster"
        - name: NUM_TOKENS
          value: "64"
        - name: DC
          value: "DC-1"
        - name: RACK
          value: "rack-1"
        - name: SNITCH
          value: GossipingPropertyFileSnitch
        ports:
        - containerPort: 7000
          name: intra-node-port
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx-port
