apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dse
spec:
  selector:
    matchLabels:
      app: dse
  serviceName: "dse"
  replicas: 2
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dse
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: dse
        image: datastax/dse-server:6.7.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: "2000Mi"
        env:
        - name: DS_LICENSE
          value: accept
        - name: SEEDS
          value: dse-0.dse.default.svc.cluster.local,dse-1.dse.default.svc.cluster.local
        - name: CLUSTER_NAME
          value: "Support_Summit"
        - name: NUM_TOKENS
          value: "32"
        - name: DC
          value: "DC-1"
        - name: RACK
          value: "rack-1"
        - name: SNITCH
          value: GossipingPropertyFileSnitch
        ports:
        - containerPort: 7000
          name: intra-node-port
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx-port
        - containerPort: 8609
          name: inter-node-msg
        - containerPort: 9042
          name: cql-port
        - containerPort: 9160
          name: thrift-port
        - containerPort: 8983
          name: solr-port
        - containerPort: 8984
          name: solr-int-node
        - containerPort: 4040
          name: spark-app-port
        - containerPort: 7077
          name: spark-int-node
        - containerPort: 7080
          name: spark-m-web
        - containerPort: 7081
          name: spark-w-web
        - containerPort: 8090
          name: spark-job
        - containerPort: 9999
          name: spark-job-jmx
        - containerPort: 18080
          name: spark-histor
        - containerPort: 8182
          name: gremlin-port
        - containerPort: 5598
          name: dsefs-public
        - containerPort: 5599
          name: dsefs-private
        - containerPort: 61621
          name: ds-agent-port
